# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZThhYjExYjlkN2YzNDk3NDM0YjdhN2NmZDVjZDFiMTQ1Yjc1ZjJhMzU0MThmZGVkOTdiM2RjYTcyZTQ5ZDlkZmVhZTA4ZjI0ZDE0MWVjODc5NDIzYjg0NWJmODY0OWI1ZmEwNTMwZDkyMTIwMmI4Y2MzZjI0YzU1NWMwODNmYTA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
